
[attack]
    attack-color = 'red' # 击打颜色, ['red', 'blue']

[communicator]
    enable = false
    serial-port = '/dev/ttyUSB0'

[isServer]
    mode = 2   # 0-不启动ISServer 1-? 2-?

[cap]
    # 读入图像旋转角度（顺时针），适配摄像头装反的情况，取值：0|90|180|270
    rotate = 0
    # true为打开视频或垃圾摄像头, false为打开摄像头
    is-video = false
    # 视频路径或垃圾摄像头路径
    video-path = "../video/全国赛part3.avi"   
    # 录视频
    record = true

# 自瞄*
[auto]
    # 参数
    thread-num = 1                                 # 线程数量
    is-dilate = false                              # 是否膨胀
    classifier-path = '../data/rm520.xml'          # 分类器文件地址
    enable-predict = true
    # 摄像头
    laji-exposure = 0.0028                                 # 垃圾摄像头曝光
    pro-exposure = 1500.0                                  # 工业摄像头曝光
    cam-model-path = '../data/camera.xml'         # 相机参数文件路径
    kp = 1.0
    ki = 0.0
    kd = 0.0
    
    
# 大符
[power]

#弹道
x = -10.0     #5(24-27)  22(22.5-25)
y = -345.0  #-300       -405
z = 150.0   #150        150


delay = 0.52#0.4 Great 0.34
maxYawError = 0.6    #0.6
maxPitchError = -0.6 #-0.4
thre = 60
close = true

# 弹道拟合
[correctTrajectory]
x = 0.0
y = 0.0
pitch = 0.0
ifAdvance = false  #是否预测空气阻力
